In [37]:
import serial, time
import pandas as pd
from IPython.display import clear_output
import numpy as np

In [ ]:


ser = serial.Serial(puerto, baudios, timeout=timeout)

# Configuración del puerto serial
puerto = 'COM5'  # Cambia por el puerto que estés usando
baudios = 9600  # Ajusta la velocidad en baudios según tu dispositivo
timeout = 1  # Tiempo de espera en segundos


#definir las columnas
column_names = ["ANGULITO","adc0", "volts0", "P0", "V0", "adc1", "volts1", "P1", "V1", "adc2", "volts2", "P2", "V2", "adc3", "volts3", "P3", "V3", "nada mi vida" ]#importante definir el numero de columnas con su respectivo nombre
# Crear un DataFrame vacío
datos = pd.DataFrame(columns=column_names)  # Ajusta las columna segun datos

try:
    while True:
        # Leer datos del puerto serial
        datos_linea = ser.readline().decode('utf-8').strip()  # Decodifica y elimina espacios

        # Convertir datos a lista
        datos_lista = datos_linea.split(',')  # Separa los datos por comas (ajustar según el separador)
        
        # Check if the number of values matches the columns
        if len(datos_lista) != len(column_names):
            print(f"Warning: Received {len(datos_lista)} values, expected {len(column_names)}")
            continue  # Skip this iteration if data length doesn't match

        # Create a new row as a DataFrame
        nueva_fila = pd.DataFrame([datos_lista], columns=column_names)
        
        # Concatenate the new row to the main DataFrame (corrected method)
        datos = pd.concat([datos, nueva_fila], ignore_index=True)
        datos['V2','V3','v1','v0'] = datos['V3','V2','V1','V0'].astype(float)
        print(datos.iloc[-1])
        clear_output(wait=True)
except KeyboardInterrupt:
    # Cerrar el puerto serial
    ser.close()
    print('Lectura de datos finalizada.')

# Mostrar el DataFrame
# Save the DataFrame to an Excel file
filename = 'rocket_data.xlsx'
datos.to_excel(filename, sheet_name='Motor Data')  # Optional: specify sheet name

print(f'DataFrame saved to Excel file: {filename}')

In [65]:
datos

,ANGULITO,adc0,volts0,P0,V0,adc1,volts1,P1,V1,adc2,volts2,P2,V2,adc3,volts3,P3,V3,nada mi vida,"(V2, V3, v1, v0)"
0,17.26,3756.00,0.70,413.12,25.97,3092.00,0.58,412.84,25.96,986.00,0.18,411.97,25.93,944.00,0.18,411.95,25.93,,25.93
1,13.04,3760.00,0.70,413.12,25.97,3071.00,0.58,412.84,25.96,989.00,0.19,411.97,25.93,946.00,0.18,411.95,25.93,,25.93
2,10.68,3761.00,0.71,413.12,25.97,3223.00,0.60,412.90,25.96,987.00,0.19,411.97,25.93,943.00,0.18,411.95,25.93,,25.93
3,3.86,3758.00,0.70,413.12,25.97,3108.00,0.58,412.85,25.96,985.00,0.18,411.97,25.93,944.00,0.18,411.95,25.93,,25.93
4,5.57,3755.00,0.70,413.12,25.97,3165.00,0.59,412.87,25.96,984.00,0.18,411.97,25.93,948.00,0.18,411.95,25.93,,25.93
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
77,13.34,3763.00,0.71,413.12,25.97,3217.00,0.60,412.90,25.96,983.00,0.18,411.97,25.93,947.00,0.18,411.95,25.93,,25.93
78,-3.33,3770.00,0.71,413.13,25.97,3150.00,0.59,412.87,25.96,987.00,0.19,411.97,25.93,949.00,0.18,411.95,25.93,,25.93
79,-0.27,3775.00,0.71,413.13,25.97,3193.00,0.60,412.89,25.96,985.00,0.18,411.97,25.93,948.00,0.18,411.95,25.93,,25.93
80,10.51,3753.00,0.70,413.12,25.97,3103.00,0.58,412.85,25.96,986.00,0.18,411.97,25.93,945.00,0.18,411.95,25.93,,25.93
81,-0.41,3778.00,0.71,413.13,25.97,3185.00,0.60,412.88,25.96,986.00,0.18,411.97,25.93,947.00,0.18,411.95,25.93,,25.93

In [70]:
import openpyxl
filename = 'rocket_data.xlsx'
datos.to_excel(filename, sheet_name='Motor Data')  # Optional: specify sheet name

print(f'DataFrame saved to Excel file: {filename}')

DataFrame saved to Excel file: rocket_data.xlsx

In [69]:
!pip install openpyxl

Collecting openpyxl
  Downloading openpyxl-3.1.2-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-1.1.0-py3-none-any.whl.metadata (1.8 kB)
Downloading openpyxl-3.1.2-py2.py3-none-any.whl (249 kB)
   ---------------------------------------- 0.0/250.0 kB ? eta -:--:--
   ---------------------------------------- 0.0/250.0 kB ? eta -:--:--
   - -------------------------------------- 10.2/250.0 kB ? eta -:--:--
   ---- ---------------------------------- 30.7/250.0 kB 330.3 kB/s eta 0:00:01
   --------- ----------------------------- 61.4/250.0 kB 409.6 kB/s eta 0:00:01
   -------------- ------------------------ 92.2/250.0 kB 525.1 kB/s eta 0:00:01
   ------------------------ ------------- 163.8/250.0 kB 756.6 kB/s eta 0:00:01
   ---------------------------------- --- 225.3/250.0 kB 919.0 kB/s eta 0:00:01
   -------------------------------------- 250.0/250.0 kB 904.7 kB/s eta 0:00:00
Downloading et_xmlfile-1.1.0-py3-none-any.whl (4.7 kB)
Installing collected packages: et-xmlfile, openpyxl
Successfully installed et-xmlfile-1.1.0 openpyxl-3.1.2

In [64]:
ser.close()
#print(datos)

In [ ]:
ser.close()

In [ ]:
a

,ANGULITO,adc0,volts0,P0,V0,adc1,volts1,P1,V1,adc2,volts2,P2,V2,adc3,volts3,P3,V3,nada mi vida
0,10.34,2272.00,0.43,0.70,1.07,1057.00,0.20,0.20,0.57,1176.00,0.22,0.25,0.63,807.00,0.15,0.09,0.39,
1,10.34,2272.00,0.43,0.70,1.07,1058.00,0.20,0.20,0.57,1174.00,0.22,0.24,0.63,822.00,0.15,0.10,0.40,
2,9.90,2272.00,0.43,0.70,1.07,1058.00,0.20,0.20,0.57,1173.00,0.22,0.24,0.63,838.00,0.16,0.10,0.41,
3,10.87,2271.00,0.43,0.70,1.07,1058.00,0.20,0.20,0.57,1175.00,0.22,0.25,0.63,872.00,0.16,0.12,0.44,
4,10.34,2273.00,0.43,0.70,1.07,1057.00,0.20,0.20,0.57,1175.00,0.22,0.25,0.63,859.00,0.16,0.11,0.43,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
174,9.90,2220.00,0.42,0.68,1.05,1023.00,0.19,0.18,0.54,1146.00,0.21,0.23,0.62,1067.00,0.20,0.20,0.57,
175,10.34,2221.00,0.42,0.68,1.05,1023.00,0.19,0.18,0.54,1146.00,0.21,0.23,0.62,1066.00,0.20,0.20,0.57,
176,10.34,2224.00,0.42,0.68,1.06,1025.00,0.19,0.18,0.55,1145.00,0.21,0.23,0.62,1067.00,0.20,0.20,0.57,
177,10.34,2195.00,0.41,0.67,1.05,1008.00,0.19,0.18,0.54,1134.00,0.21,0.23,0.61,1057.00,0.20,0.20,0.57,
178,11.22,2181.00,0.41,0.66,1.04,994.00,0.19,0.17,0.53,1113.00,0.21,0.22,0.60,1041.00,0.20,0.19,0.56,